# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('ts', models.DateTimeField()),
                ('pub_key', models.CharField(max_length=256)),
            ],
        ),
    ]
